In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# Here, before running the code please change the Folder name from "NLPFinal" to the required one.
import os
os.chdir("/content/drive/MyDrive/NLPFinal")

### Read training, dev and unlabeled test data

The following provides a starting code (Python 3) of how to read the labeled training and dev cipher text, and unlabeled test cipher text, into lists.

In [3]:
train, dev, test = [], [], []

In [4]:
for x in open('./train_enc.tsv', encoding='utf-8'):
    x = x.rstrip('\n\r').split('\t')
    # x[0] will be the label (0 or 1), and x[1] will be the ciphertext sentence.
    x[0] = int(x[0]) 
    train.append(x)
print (len(train))
print (train[:3])

16220
[[0, 'lkêcê yoúc cêêö y#êjl lw mówám Újám j Úêê# ütlk Úol lkêú z#ê ctöé8ú ówl xoóóú éê#xw#öê#c .'], [0, '6êcétlê jolêot8 zc éê#xw#öjóáê , tl zc j #jlkê# 8tcl8êcc jöÚ8ê 6wüó lkê öt668ê wx lkê #wj6 , ükê#ê lkê lkêöjltá t#wótêc j#ê lww wÚ2twoc jó6 lkê cê+oj8 éw8tltác lww cöoy .'], [0, 'tx lktc kw8t6jú öw2tê tc coééwcê6 lw Úê j ytxl , cwöêÚw6ú oóü#jééê6 tl êj#8ú , lwwm wol j88 lkê yww6 cloxx , jó6 8êxl Úêktó6 lkê á#jé ( 8tlê#j88ú ) .']]


In [5]:
for x in open('./dev_enc.tsv', encoding='utf-8'):
    x = x.rstrip('\n\r').split('\t')
    # x[0] will be the label (0 or 1), and x[1] will be the ciphertext sentence.
    x[0] = int(x[0]) 
    dev.append(x)
print (len(dev))
print (dev[:3])

2027
[[1, 'ów8jó Ú#j2ê8ú l#êj6c ükê#ê xêü jöê#tájó xt8öc 6j#ê lw 6ê82ê 77 tólw lkê üw#86 wx jöÚt2j8êóáê jó6 jöÚtyotlú <<<'], [0, 'ê2êó öo#ékú zc ê+éê#l áwötá ltötóy jó6 xjöê6 ákj#tcöj áj ózl #êcáoê lktc êxxw#l .'], [1, 'üt88 jcco#ê68ú #jóm jc wóê wx lkê á8ê2ê#êcl , öwcl 6êáêélt2ê8ú jöoctóy áwöê6têc wx lkê úêj# .']]


#### Different from 'train' and 'dev' that are both list of tuples, 'test' will be just a list.

In [6]:
for x in open('./test_enc_unlabeled.tsv', encoding='utf-8'):
    x = x.rstrip('\n\r')
    test.append(x)
print (len(test))
print (test[:3])

2028
['j 6t6jáltá jó6 6o88 6wáoöêólj#ú y8w#txútóy cwxlüj#ê jój#ákú .', 'ówlktóy cltámc , #êj88ú , ê+áêél j 8tóyê#tóy á#êêétóêcc wóê xêê8c x#wö Úêtóy 6#jyyê6 lk#woyk j cj6 , cw#6t6 oót2ê#cê wx yoóc , 6#oyc , j2j#táê jó6 6jöjyê6 6#êjöc .', 'öo#ékú jó6 üt8cwó jáloj88ú öjmê j é#êllú yww6 lêjö <<< Úol lkê é#wvêál co##woó6tóy lkêö tc 6tcl#êcctóy8ú #wlê .']


#### You can split every sentence into lists of words by white spaces.

In [7]:
train_split = [[x[0], x[1].split(' ')] for x in train]
dev_split = [[x[0], x[1].split(' ')] for x in dev]
test_split = [[x.split(' ')] for x in test]

### Main Code Body

You may choose to experiment with different methods using your program. However, you need to embed the training and inference processes at here. We will use your prediction on the unlabeled test data to grade, while checking this part to understand how your method has produced the predictions.

In [8]:
X_train=[]
Y_train=[]
X_val=[]
Y_val=[]
for data in train:
  X_train.append(data[1])
  Y_train.append(int(data[0]))
for data in dev:
  X_val.append(data[1])
  Y_val.append(int(data[0]))
print(X_train[:2])

['lkêcê yoúc cêêö y#êjl lw mówám Újám j Úêê# ütlk Úol lkêú z#ê ctöé8ú ówl xoóóú éê#xw#öê#c .', '6êcétlê jolêot8 zc éê#xw#öjóáê , tl zc j #jlkê# 8tcl8êcc jöÚ8ê 6wüó lkê öt668ê wx lkê #wj6 , ükê#ê lkê lkêöjltá t#wótêc j#ê lww wÚ2twoc jó6 lkê cê+oj8 éw8tltác lww cöoy .']


In [9]:
X_test=[]
for data in test:
  X_test.append(data)
print(len(X_test))
print(X_test[:2])

2028
['j 6t6jáltá jó6 6o88 6wáoöêólj#ú y8w#txútóy cwxlüj#ê jój#ákú .', 'ówlktóy cltámc , #êj88ú , ê+áêél j 8tóyê#tóy á#êêétóêcc wóê xêê8c x#wö Úêtóy 6#jyyê6 lk#woyk j cj6 , cw#6t6 oót2ê#cê wx yoóc , 6#oyc , j2j#táê jó6 6jöjyê6 6#êjöc .']


### Checking for the dataset if it is imbalanced.

In [10]:
zero_count=0
one_count=0
for data in Y_train:
  if data==0:
    zero_count+=1
  elif data==1:
    one_count+=1
print("zero count",zero_count)
print("one_count",one_count)
if len(Y_train)==(zero_count+one_count):
  print("The data has no null or inappropriate data")

zero count 7999
one_count 8221
The data has no null or inappropriate data


## Here, since both the values of zero and one are same and the data is balanced, we don't need to provide any additional mechanism to handle the imbalanced dataset.

In [11]:
# Eventually, results need to be a list of 2028 0 or 1's
results = []

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
# text_classification=Pipeline([('tfidf', TfidfVectorizer(ngram_range = (1, 3))),
#                      ('classification', SVC(kernel="linear")),])
# text_classification.fit(X_train,Y_train)

In [14]:
# text_classification=Pipeline([('tfidf', TfidfVectorizer(ngram_range = (1, 3),binary=True)),
#                      ('classification', SVC(kernel="linear")),])
# text_classification.fit(X_train,Y_train)

BERT TRY

In [15]:
# !pip install tensorflow-text
# import tensorflow as tf
# import tensorflow_hub as hub
# import tensorflow_text as text
# bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
# bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")
# def get_sentence_embeding(sentences):
#     preprocessed_text = bert_preprocess(sentences)
#     return bert_encoder(preprocessed_text)['pooled_output']
# # Bert layers
# text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
# preprocessed_text = bert_preprocess(text_input)
# outputs = bert_encoder(preprocessed_text)
# # Neural network layers
# l = tf.keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
# l = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(l)
# model = tf.keras.Model(inputs=[text_input], outputs = [l])
# model.summary()
# METRICS = [
#       tf.keras.metrics.BinaryAccuracy(name='accuracy')
# ]
# model.compile(optimizer='adam',
#               loss='binary_crossentropy',
#               metrics=METRICS)
# from tensorflow.keras.callbacks import EarlyStopping
# early_stopping = EarlyStopping(monitor= 'val_accuracy', 
#                                mode = 'max',
#                                patience=10, 
#                                verbose=1)
# model.fit(X_train, Y_train, validation_data=[X_val,Y_val], epochs=50, callbacks=[early_stopping])

Fast-Text and Bidirectional LSTM- Around 87-88%

TFID and Neural Network: 88%

In [16]:
text_classification=Pipeline([('tfidf', TfidfVectorizer(ngram_range = (1, 2),binary=True)),
                     ('classification', SVC(kernel="linear")),])
text_classification.fit(X_train,Y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(binary=True, ngram_range=(1, 2))),
                ('classification', SVC(kernel='linear'))])

In [17]:
predictions=text_classification.predict(X_val)

In [18]:
from sklearn import metrics
print(metrics.confusion_matrix(Y_val,predictions))

[[852 100]
 [104 971]]


In [19]:
print(metrics.classification_report(Y_val,predictions))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89       952
           1       0.91      0.90      0.90      1075

    accuracy                           0.90      2027
   macro avg       0.90      0.90      0.90      2027
weighted avg       0.90      0.90      0.90      2027



In [20]:
print(metrics.accuracy_score(Y_val,predictions))

0.8993586581154416


In [21]:
Y_test=text_classification.predict(X_test)

In [22]:
print(Y_test[:5])
print(Y_test[-5:])

[0 0 0 0 0]
[0 1 1 1 1]


In [23]:
#Checking the data only
print(len(Y_test))
zero_count=0
one_count=0
for data in Y_test:
  if data==0:
    zero_count+=1
  elif data==1:
    one_count+=1
print("zero count",zero_count)
print("One count",one_count)


2028
zero count 1024
One count 1004


In [24]:
for val in Y_test:
  results.append(val)

### Output Prediction Result File

You will need to submit a prediction result file. It should have 2028 lines, every line should be either 0 or 1, which is your model's prediction on the respective test set instance.

In [25]:
# suppose you had your model's predictions on the 2028 test cases read from test_enc_unlabeled.tsv, and 
#those results are in the list called 'results'
assert (len(results) == 2028)

In [26]:
# make sure the results are not float numbers, but intergers 0 and 1
results = [int(x) for x in results]

In [27]:
# write your prediction results to 'upload_predictions.txt' and upload that later
with open('upload_predictions.txt', 'w', encoding = 'utf-8') as fp:
    for x in results:
        fp.write(str(x) + '\n')